<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace App\Grpc\GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        // \AppGrpc\GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
·
hello.protoApp.Grpc.Hello"
HelloReq
name (	"+

HelloReply
name (	
message (	2j
GreeterServiceX
SayHello.App.Grpc.Hello.HelloReq.App.Grpc.Hello.HelloReply"Ç”‰ì/v1/say/{name}BZ./;pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

